// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD_mFqU5Z7mUaR6ZuObNAJieZ66tr2AroY',
    appId: '1:38359988657:web:3143c1a8b7eb8c33d62590',
    messagingSenderId: '38359988657',
    projectId: 'social-media-app-4a9c3',
    authDomain: 'social-media-app-4a9c3.firebaseapp.com',
    storageBucket: 'social-media-app-4a9c3.firebasestorage.app',
    measurementId: 'G-LLC178HDSR',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAA5M221pDYl9k1alDhpIxKQaqUM8KFDyQ',
    appId: '1:38359988657:android:5ce082c54419f819d62590',
    messagingSenderId: '38359988657',
    projectId: 'social-media-app-4a9c3',
    storageBucket: 'social-media-app-4a9c3.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDTOG9Ud83Wl9BUT0QWwYzddVUZFnV4uOI',
    appId: '1:38359988657:ios:2e18e9b085adf8e5d62590',
    messagingSenderId: '38359988657',
    projectId: 'social-media-app-4a9c3',
    storageBucket: 'social-media-app-4a9c3.firebasestorage.app',
    iosBundleId: 'com.example.minimalsocialmedia',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDTOG9Ud83Wl9BUT0QWwYzddVUZFnV4uOI',
    appId: '1:38359988657:ios:2e18e9b085adf8e5d62590',
    messagingSenderId: '38359988657',
    projectId: 'social-media-app-4a9c3',
    storageBucket: 'social-media-app-4a9c3.firebasestorage.app',
    iosBundleId: 'com.example.minimalsocialmedia',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyD_mFqU5Z7mUaR6ZuObNAJieZ66tr2AroY',
    appId: '1:38359988657:web:fd3cbeee45948a4ed62590',
    messagingSenderId: '38359988657',
    projectId: 'social-media-app-4a9c3',
    authDomain: 'social-media-app-4a9c3.firebaseapp.com',
    storageBucket: 'social-media-app-4a9c3.firebasestorage.app',
    measurementId: 'G-T01214YC36',
  );
}
